version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: qwerasdf1!
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: